Repository monstar-lab-oss/admin-panel-template-reactjs, pull requests merged in 2021-05, with the labels that each got.

#68 Chore/GitHub actions
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
Labels: chore

#69 Fix: netlify
  public/_redirects
Labels: fix

#71 Feature/improve button
  src/components/atoms/Button/Button.tsx
  src/helpers/util.helper.ts
Labels: feature

#72 Feature/debounced input
  src/components/atoms/DebouncedInput/DebouncedInput.tsx
  src/components/molecules/PageFilter/components/FilterItem/FilterItem.tsx
  src/components/molecules/PageFilter/page-filter.md
  src/features/localization/config/localization.config.ts
  src/features/settings/screens/UsersScreen/components/UsersFilter/UsersFilter.tsx
Labels: feature

#81 chore: Fix retina image blur issue
  src/index.scss
Labels: chore

#83 Feature/improve unsaved prompt updates
  src/components/atoms/Form/Form.tsx
  src/components/atoms/FormModal/FormModal.tsx
  src/components/molecules/Navigation/components/NavRightContent/NavRightContent.tsx
  src/features/localization/config/localization.config.ts
  src/features/settings/api/users.api.ts
  src/features/settings/helpers/users.helper.ts
  src/features/settings/redux/users.slice.ts
  src/features/settings/screens/UsersScreen/components/UserRoleModal/UserRoleModal.tsx
  src/features/settings/screens/UsersScreen/components/UsersModal/UsersModal.tsx
  src/features/settings/settings.ts
  src/features/settings/types/user.types.ts
  src/helpers/user.helper.ts
  src/helpers/util.helper.ts
  src/hooks/useShowModal.ts
  src/hooks/useUnsavedPrompt.tsx
Labels: feature

#82 Feature(improve-unsaved-prompt): improving and updating Form Modal functionality
  src/components/atoms/Form/Form.tsx
  src/components/atoms/FormModal/FormModal.tsx
  src/components/atoms/ModalConfirm/ModalConfirm.tsx
  src/components/molecules/Navigation/components/NavRightContent/NavRightContent.tsx
  src/features/localization/config/localization.config.ts
  src/features/settings/api/users.api.ts
  src/features/settings/helpers/users.helper.ts
  src/features/settings/redux/users.slice.ts
  src/features/settings/screens/UsersScreen/UsersScreen.tsx
  src/features/settings/screens/UsersScreen/components/UserRoleModal/UserRoleModal.tsx
  src/features/settings/screens/UsersScreen/components/UsersModal/UsersModal.tsx
  src/features/settings/settings.ts
  src/features/settings/types/user.types.ts
  src/helpers/user.helper.ts
  src/helpers/util.helper.ts
  src/hooks/useShowModal.ts
  src/hooks/useUnsavedPrompt.tsx
Labels: feature
