Repository monstar-lab-oss/admin-panel-template-reactjs, pull requests merged in 2021-09, with the labels that each got.

#106 Feature/login redirect
  src/App.tsx
  src/api/api.ts
  src/components/layouts/BlankLayout/BlankLayout.tsx
  src/components/molecules/Navigation/components/NavRightContent/NavRightContent.tsx
  src/features/auth/api/auth.api.ts
  src/features/auth/auth.md
  src/features/auth/auth.ts
  src/features/auth/constants/auth.endpoints.ts
  src/features/auth/constants/auth.keys.ts
  src/features/auth/constants/auth.paths.ts
  src/features/auth/helpers/auth.helpers.ts
  src/features/auth/hooks/useRedirectAfterLogin.ts
  src/features/auth/redux/auth.slice.ts
  src/features/auth/routes/auth.routes.ts
  src/features/auth/screens/LoginScreen/LoginScreen.module.scss
  src/features/auth/screens/LoginScreen/LoginScreen.tsx
  src/features/auth/types/auth.types.ts
  src/features/localization/config/localization.config.ts
  src/redux/root-reducer.ts
  src/routes/Routes.tsx
  src/routes/components/LoginRedirect/LoginRedirect.tsx
  src/routes/routes.config.ts
  src/types/route.types.ts
Labels: feature

#114 Husky migration from v4.x to v7.x
  .husky/pre-commit
  package.json
  yarn.lock
Labels: enhancement

#120 No files matching yarn format mac/windows fix
  package.json
Labels: bug

#118 migration: Prettier `v2.2.x` to `v2.4.x`
  .prettierrc.js
  package.json
  src/components/atoms/DebouncedInput/DebouncedInput.tsx
  src/features/localization/helpers/localization.helpers.ts
  src/hooks/useSearchParams.ts
  yarn.lock
Labels: fix
